### ISSUE TITLE
linter should verify the path starts with `/.`

### ISSUE THREAD

**Issue by dbarrosop** [networktocode/yangify#14]
For instance:

```
 class VlanConfigVlans(Translator):
     class Yangify(TranslatorData):
-        path = "ntc-vlan:vlan/config/vlans"
+        path = "/ntc-vlan:vlan/config/vlans"
```

The first one should trigger a warning.

**Comment by dgjustice** [comment]
@dbarrosop How do you suggest we accomplish this?  Should this be a plugin for an existing framework or simply a bespoke script we run against this repo?  Thanks!

**Comment by dgjustice** [comment]
David's comments from DM:
> yangify already comes with a linter so it’d be a matter of extending it to make sure the path starts with a /

**Comment by FragmentedPacket** [comment]
I'm starting work on this and believe I have it implemented, but needing to change a bunch of tests for the linter.

It appears that a lot of the linter data within the tests directory have paths that do not begin with the `/` so I'm wondering if I should update those paths to include the the `/` or just account for those in the expected data it is to get back?

**Comment by dgjustice** [comment]
I think it might be best to reflect "best practice" in the test suite and update the paths.  We just need ot make sure the warning is signaled with an appropriate test method.
