### ISSUE TITLE
Step 3 doesn't work

### ISSUE THREAD

**Issue by GoreNetwork** [networktocode/yangify#4]
$ make build_test_containers 
Gives the error
C:\yangifycrap\yangify\docs>make build_test_containers
'make' is not recognized as an internal or external command,
operable program or batch file.

**Comment by jathanism** [comment]
We need to callout that Linux should be used for now since there is no `make` on Windows by default.

**Comment by dbarrosop** [comment]
I closed this issue, feel free to reopen if you think there is something missing.

Thanks!
