### ISSUE TITLE
Parsing Quickstart guide yang models directory is incorrect in documentation

### ISSUE THREAD

**Issue by theillego** [networktocode/yangify#6]
In the parsing quickstart guide documentation, after the install pyang step, please change the directory to /yangify/docs/tutorials/yang/yang-modules/openconfig. So the command will be pyang -f tree yangify/docs/tutorials/yang/yang-modules/openconfig/openconfig-lldp.yang when in the root directory

**Comment by dbarrosop** [comment]
Will do! Thanks! And next time PRs are welcomed ;)
