### ISSUE TITLE
BugFix: Makefile - jupyter build

### ISSUE THREAD

**Issue by FragmentedPacket** [networktocode/yangify#8]
`make jupyter` does not actually assign port to the docker container (from Windows perspective at least):

Two possible fixes:
- Add `-p 8888:8888` to `DOCKER` variable (L6)
- Change L106 from `${DOCKER}` to `${DEV_JUPYTER}`

**Comment by dbarrosop** [comment]
Thanks, fixing soon. Next time don't hesitate to send a PR :)
