### ISSUE TITLE
Vendor models included in yangify?

### ISSUE THREAD

**Issue by raddessi** [networktocode/yangify#9]
Are you planning to include vendor-specific (IOS/EOS/JunOS/etc) translator models in the yangify module and load them like napalm does with their drivers or will it be up to the user to handle the creation of those?

**Comment by itdependsnetworks** [comment]
Our goal is to build models that will always be vendor neutral, however the translators and parsers will be per vendor os, based on that neutral model. The actual translation and parsing will happen in a to be released project outside of yangify called rosetta.

You could use this library to do what you are asking for, but I think going the Rosetta route will be the best way forward.

**Comment by raddessi** [comment]
Fantastic, ok, that makes it more clear. Will you post updates about Rosetta here, and will it be released under the networktocode account?

Thanks for the clarification :)

**Comment by itdependsnetworks** [comment]
Yes

**Comment by raddessi** [comment]
I can't wait to see it then. Thanks for the work, you can close this one out.

**Comment by itdependsnetworks** [comment]
One point of clarification, will post updates on network to code blog, not here. I commented too fast before.
